name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: KaMeHb-UA/action-firebase-cloud-config@main
        env:
          config.my-test-env: sometestvalue
        with:
          config: |
            test-str: with-val1
            test-arr:
              - testv1
              - testv2
              - ${my-test-env}
